// The content of this file was generated by IBM Cloud
// Do not modify it as it might get overridden

package services // fix once we know what package
// The content of this file was generated by IBM Cloud
// Do not modify it as it might get overridden
import (

)
from ibmcloudenv import IBMCloudEnv

//from . import service_manager

IBMCloudEnv.Initalize()

// GENERATE IMPORT HERE

func initServices() {
    // GENERATE HERE
    return
}
